apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: notif-smtp-spc
  namespace: notifications
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:ap-northeast-2:086015456585:secret:notif/smtp-ehaQQu"
        objectType: "secretsmanager"
        objectAlias: "smtp.json"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-microservice
  namespace: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-restapp
  template:
    metadata:
      labels:
        app: notification-restapp
    spec:
      serviceAccountName: notification-sa
      containers:
        - name: notification-service
          image: stacksimplify/kube-notifications-microservice:4.0.0-AWS-XRay
          ports:
            - containerPort: 8096
          volumeMounts:
            - name: aws-secrets
              mountPath: /mnt/secrets-store
              readOnly: true
          env:
            - name: AWS_MAIL_SERVER_HOST
              value: "email-smtp.ap-northeast-2.amazonaws.com"
            - name: SMTP_SECRET_FILE
              value: "/mnt/secrets-store/smtp.json"
      volumes:
        - name: aws-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "notif-smtp-spc"
